[package]
name = "ravn"
version = "0.0.0"
edition = "2021"
description = "ğŸ¦â€â¬› Ravn"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ravn-bot/ravn"
exclude = ["/messages"]

[dependencies]
